const samplePhotos=Array.from({length:50},(_,i)=>`sample/Photos/40864709_${i+1}.jpg`);
const sample={id:'40864709',address:'2 OAK KNOLL Drive',city:'Hamilton, Ontario',neighbourhood:'Westdale',tags:[],cover:samplePhotos[0],photos:samplePhotos,floorplans:[{name:'Ground Floor',url:'sample/Floorplans/ground_floor_487.jpg'},{name:'2nd Floor',url:'sample/Floorplans/2nd_floor_558.jpg'},{name:'3rd Floor',url:'sample/Floorplans/3rd_floor_745.jpg'},{name:'Basement',url:'sample/Floorplans/basement_166.jpg'}],listing:[{name:'Full-page listing screenshot',url:'sample/Listing/screencapture-realtor-ca-real-estate-30301826-2-oak-knoll-drive-hamilton-2026-09-19-10_30_33.png'},{name:'Listing PDF',url:'sample/Listing/36277012-18b6-4546-9422-ed69d5c5f05b.pdf'}],video:'https://tours.vogelcreative.ca/2oakknolldrive',favorite:false,notes:''};
let properties=[sample],favOnly=false;
const $=s=>document.querySelector(s), grid=$('#grid'), lib=$('#libraryView'), detailView=$('#detailView'), back=$('#back');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function metaKey(p){return `listing-library:${p.address}`}
function loadMeta(p){try{const m=JSON.parse(localStorage.getItem(metaKey(p))||'{}');Object.assign(p,{city:m.city??p.city,neighbourhood:m.neighbourhood??p.neighbourhood,tags:Array.isArray(m.tags)?m.tags:(p.tags||[]),notes:m.notes??p.notes,favorite:m.favorite??p.favorite})}catch{}}
function saveMeta(p){localStorage.setItem(metaKey(p),JSON.stringify({city:p.city,neighbourhood:p.neighbourhood,tags:p.tags||[],notes:p.notes||'',favorite:!!p.favorite}))}
loadMeta(sample);
function render(){const q=$('#search').value.toLowerCase();const shown=properties.filter(p=>(!favOnly||p.favorite)&&(`${p.address} ${p.city} ${p.neighbourhood||''} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q)));$('#count').textContent=`${shown.length} ${shown.length===1?'property':'properties'}`;grid.innerHTML=shown.map(p=>`<article class="card" data-id="${esc(p.id)}"><div class="cover" style="background-image:url('${p.cover}')"><button class="heart" data-fav="${esc(p.id)}">${p.favorite?'♥':'♡'}</button></div><div class="cardBody"><h3>${esc(p.address)}</h3><div class="meta">${esc([p.neighbourhood,p.city].filter(Boolean).join(' · '))}</div>${p.tags?.length?`<div class="cardTags">${p.tags.slice(0,3).map(t=>`<span>${esc(t)}</span>`).join('')}</div>`:''}</div></article>`).join('');}
grid.onclick=e=>{const f=e.target.closest('[data-fav]');if(f){e.stopPropagation();const p=properties.find(x=>x.id===f.dataset.fav);p.favorite=!p.favorite;saveMeta(p);render();return}const c=e.target.closest('.card');if(c)openProperty(properties.find(x=>x.id===c.dataset.id));};
function openProperty(p){lib.classList.add('hidden');detailView.classList.remove('hidden');back.classList.remove('hidden');const chips=[`<span class="chip">Listing ${esc(p.id)}</span>`,p.photos.length?`<span class="chip">${p.photos.length} photos</span>`:'',p.floorplans.length?`<span class="chip">${p.floorplans.length} floorplans</span>`:''].join('');const tabs=[['photos','Photos',p.photos.length],['floorplans','Floorplans',p.floorplans.length],['listing','Listing',p.listing.length],['video','Video',!!p.video],['notes','Notes',true]].filter(x=>x[2]);detailView.innerHTML=`<div class="hero" style="background-image:url('${p.cover}')"><div class="heroText"><h2>${esc(p.address)}</h2><p>${esc([p.neighbourhood,p.city].filter(Boolean).join(' · '))}</p></div></div><div class="detailTop"><div class="chips">${chips}</div><button class="secondary" id="detailFav">${p.favorite?'♥ Favourite':'♡ Favourite'}</button></div><nav class="tabs">${tabs.map((x,i)=>`<button class="tab ${i===0?'active':''}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</nav><div id="panel"></div>`;const panel=$('#panel');
function tab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));if(name==='photos')panel.innerHTML=`<div class="gallery">${p.photos.map((x,i)=>`<img src="${x}" loading="lazy" data-viewer="photos" data-index="${i}" tabindex="0" alt="Property photo ${i+1}">`).join('')}</div>`;if(name==='floorplans')panel.innerHTML=`<div class="gallery floorplans">${p.floorplans.map((x,i)=>`<figure><img src="${x.url}" loading="lazy" data-viewer="floorplans" data-index="${i}" tabindex="0" alt="${esc(x.name)}"><figcaption>${esc(x.name)}</figcaption></figure>`).join('')}</div>`;if(name==='listing')panel.innerHTML=p.listing.map(x=>`<div class="fileCard"><span>${esc(x.name)}</span><a href="${x.url}" target="_blank">Open ↗</a></div>`).join('');if(name==='video')panel.innerHTML=p.video?`<div class="fileCard"><span>Property video / virtual tour</span><a href="${p.video}" target="_blank">Open video ↗</a></div>`:'';if(name==='notes')panel.innerHTML=`<div class="notes"><div class="metaFields"><label>City<input id="cityField" value="${esc(p.city)}" placeholder="City"></label><label>Neighbourhood<input id="neighbourhoodField" value="${esc(p.neighbourhood)}" placeholder="Neighbourhood"></label></div><label class="fieldLabel">Tags<input id="tagsField" value="${esc((p.tags||[]).join(', '))}" placeholder="e.g. Hamilton, Westdale, Tudor Revival"></label><label class="fieldLabel">Notes<textarea id="notes" placeholder="Add notes about this property…">${esc(p.notes||'')}</textarea></label><div class="saveStatus" id="saveStatus">Saved locally in this browser</div></div>`;wireViewers();if(name==='notes')wireMeta();}
function wireMeta(){const save=()=>{p.city=$('#cityField').value.trim();p.neighbourhood=$('#neighbourhoodField').value.trim();p.tags=$('#tagsField').value.split(',').map(x=>x.trim()).filter(Boolean);p.notes=$('#notes').value;saveMeta(p);$('#saveStatus').textContent='Saved';};['#cityField','#neighbourhoodField','#tagsField','#notes'].forEach(s=>$(s).addEventListener('input',save));}
function wireViewers(){panel.querySelectorAll('[data-viewer]').forEach(img=>{const open=()=>{const items=img.dataset.viewer==='photos'?p.photos:p.floorplans.map(x=>x.url);openViewer(items,Number(img.dataset.index),img.dataset.viewer==='photos'?'Photo':'Floorplan')};img.addEventListener('click',open);img.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
tab(tabs[0][0]);document.querySelector('.tabs').onclick=e=>{if(e.target.dataset.tab)tab(e.target.dataset.tab)};$('#detailFav').onclick=()=>{p.favorite=!p.favorite;saveMeta(p);openProperty(p)};}
function openViewer(items,start=0,label='Photo'){let index=start;const overlay=document.createElement('div');overlay.className='viewer';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.innerHTML=`<button class="viewerClose" aria-label="Close viewer">×</button><button class="viewerNav viewerPrev" aria-label="Previous">‹</button><figure><img><figcaption></figcaption></figure><button class="viewerNav viewerNext" aria-label="Next">›</button>`;document.body.appendChild(overlay);const image=overlay.querySelector('img'),caption=overlay.querySelector('figcaption');const show=()=>{image.src=items[index];image.alt=`${label} ${index+1}`;caption.textContent=`${index+1} / ${items.length}`};const close=()=>{document.removeEventListener('keydown',keys);overlay.remove()};const move=d=>{index=(index+d+items.length)%items.length;show()};const keys=e=>{if(e.key==='Escape')close();else if(e.key==='ArrowLeft')move(-1);else if(e.key==='ArrowRight')move(1)};overlay.querySelector('.viewerClose').onclick=close;overlay.querySelector('.viewerPrev').onclick=e=>{e.stopPropagation();move(-1)};overlay.querySelector('.viewerNext').onclick=e=>{e.stopPropagation();move(1)};overlay.onclick=e=>{if(e.target===overlay)close()};overlay.querySelector('figure').onclick=e=>e.stopPropagation();document.addEventListener('keydown',keys);show();overlay.querySelector('.viewerClose').focus()}
back.onclick=()=>{detailView.classList.add('hidden');lib.classList.remove('hidden');back.classList.add('hidden');render()};$('#search').oninput=render;$('#favFilter').onclick=()=>{favOnly=!favOnly;$('#favFilter').textContent=favOnly?'♥':'♡';render()};
function floorName(fn){const s=fn.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').toLowerCase();if(s.includes('ground'))return'Ground Floor';if(s.includes('basement'))return'Basement';if(s.match(/(^| )2(nd)?( |$)/))return'2nd Floor';if(s.match(/(^| )3(rd)?( |$)/))return'3rd Floor';if(s.match(/(^| )1(st)?( |$)/))return'1st Floor';return fn.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ')}
async function scanProperty(dir){const p={id:dir.name,address:dir.name,city:'',neighbourhood:'',tags:[],photos:[],floorplans:[],listing:[],video:'',favorite:false,notes:''};for await(const [name,h] of dir.entries()){if(h.kind!=='directory')continue;const kind=name.toLowerCase();for await(const [fn,fh] of h.entries()){if(fh.kind!=='file')continue;const file=await fh.getFile(),url=URL.createObjectURL(file);if(kind==='photos'&&/\.(jpe?g|png|webp)$/i.test(fn))p.photos.push({fn,url});else if(kind==='floorplans'&&/\.(jpe?g|png|webp)$/i.test(fn))p.floorplans.push({name:floorName(fn),url});else if(kind==='listing')p.listing.push({name:fn,url});else if(kind==='video'&&fn.endsWith('.webloc')){const txt=await file.text();p.video=(txt.match(/<string>(https?:\/\/[^<]+)<\/string>/)||[])[1]||'';}}}p.photos.sort((a,b)=>(parseInt(a.fn.match(/_(\d+)\./)?.[1])||0)-(parseInt(b.fn.match(/_(\d+)\./)?.[1])||0));p.photos=p.photos.map(x=>x.url);p.cover=p.photos[0]||'';loadMeta(p);return p;}
$('#openLibrary').onclick=async()=>{if(!window.showDirectoryPicker){alert('Folder access is not supported in this browser. Try Chrome or Edge on desktop.');return}try{const root=await showDirectoryPicker();const found=[];for await(const [,h] of root.entries())if(h.kind==='directory'){const p=await scanProperty(h);if(p.photos.length||p.listing.length||p.floorplans.length)found.push(p)}if(found.length){properties=found;render();}}catch(e){if(e.name!=='AbortError')alert('Could not open that folder.');}};render();
