const samplePhotos=Array.from({length:50},(_,i)=>`sample/Photos/40864709_${i+1}.jpg`);
const sample={id:'40864709',address:'2 OAK KNOLL Drive',city:'Hamilton, Ontario',neighbourhood:'Westdale',cover:samplePhotos[0],photos:samplePhotos,floorplans:['sample/Floorplans/ground_floor_487.jpg','sample/Floorplans/2nd_floor_558.jpg','sample/Floorplans/3rd_floor_745.jpg','sample/Floorplans/basement_166.jpg'],listing:[{name:'Full-page listing screenshot',url:'sample/Listing/screencapture-realtor-ca-real-estate-30301826-2-oak-knoll-drive-hamilton-2026-09-19-10_30_33.png'},{name:'Listing PDF',url:'sample/Listing/36277012-18b6-4546-9422-ed69d5c5f05b.pdf'}],video:'https://tours.vogelcreative.ca/2oakknolldrive',favorite:false,notes:''};
let properties=[sample],favOnly=false;
const $=s=>document.querySelector(s), grid=$('#grid'), lib=$('#libraryView'), detailView=$('#detailView'), back=$('#back');
function render(){const q=$('#search').value.toLowerCase();const shown=properties.filter(p=>(!favOnly||p.favorite)&&(`${p.address} ${p.city} ${p.neighbourhood||''}`.toLowerCase().includes(q)));$('#count').textContent=`${shown.length} ${shown.length===1?'property':'properties'}`;grid.innerHTML=shown.map((p,i)=>`<article class="card" data-id="${p.id}"><div class="cover" style="background-image:url('${p.cover}')"><button class="heart" data-fav="${p.id}">${p.favorite?'♥':'♡'}</button></div><div class="cardBody"><h3>${p.address}</h3><div class="meta">${[p.neighbourhood,p.city].filter(Boolean).join(' · ')}</div></div></article>`).join('');}
grid.onclick=e=>{const f=e.target.closest('[data-fav]');if(f){e.stopPropagation();const p=properties.find(x=>x.id===f.dataset.fav);p.favorite=!p.favorite;render();return}const c=e.target.closest('.card');if(c)openProperty(properties.find(x=>x.id===c.dataset.id));};
function openProperty(p){lib.classList.add('hidden');detailView.classList.remove('hidden');back.classList.remove('hidden');detailView.innerHTML=`<div class="hero" style="background-image:url('${p.cover}')"><div class="heroText"><h2>${p.address}</h2><p>${[p.neighbourhood,p.city].filter(Boolean).join(' · ')}</p></div></div><div class="detailTop"><div class="chips"><span class="chip">Listing ${p.id}</span><span class="chip">${p.photos.length} photos</span><span class="chip">${p.floorplans.length} floorplans</span></div><button class="secondary" id="detailFav">${p.favorite?'♥ Favourite':'♡ Favourite'}</button></div><nav class="tabs"><button class="tab active" data-tab="photos">Photos</button><button class="tab" data-tab="floorplans">Floorplans</button><button class="tab" data-tab="listing">Listing</button><button class="tab" data-tab="video">Video</button><button class="tab" data-tab="notes">Notes</button></nav><div id="panel"></div>`;const panel=$('#panel');function tab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));if(name==='photos')panel.innerHTML=`<div class="gallery">${p.photos.map(x=>`<img src="${x}" loading="lazy">`).join('')}</div>`;if(name==='floorplans')panel.innerHTML=`<div class="gallery floorplans">${p.floorplans.map(x=>`<img src="${x}" loading="lazy">`).join('')}</div>`;if(name==='listing')panel.innerHTML=p.listing.map(x=>`<div class="fileCard"><span>${x.name}</span><a href="${x.url}" target="_blank">Open ↗</a></div>`).join('');if(name==='video')panel.innerHTML=`<div class="fileCard"><span>Property video / virtual tour</span><a href="${p.video}" target="_blank">Open video ↗</a></div>`;if(name==='notes')panel.innerHTML=`<div class="notes"><textarea id="notes" placeholder="Add notes about this property…">${p.notes||''}</textarea></div>`;}tab('photos');document.querySelector('.tabs').onclick=e=>{if(e.target.dataset.tab)tab(e.target.dataset.tab)};$('#detailFav').onclick=()=>{p.favorite=!p.favorite;openProperty(p)};}
back.onclick=()=>{detailView.classList.add('hidden');lib.classList.remove('hidden');back.classList.add('hidden');render()};$('#search').oninput=render;$('#favFilter').onclick=()=>{favOnly=!favOnly;$('#favFilter').textContent=favOnly?'♥':'♡';render()};
async function scanProperty(dir){const p={id:dir.name,address:dir.name,city:'',neighbourhood:'',photos:[],floorplans:[],listing:[],video:'',favorite:false};for await(const [name,h] of dir.entries()){if(h.kind!=='directory')continue;const kind=name.toLowerCase();for await(const [fn,fh] of h.entries()){if(fh.kind!=='file')continue;const file=await fh.getFile(),url=URL.createObjectURL(file);if(kind==='photos'&&/\.(jpe?g|png|webp)$/i.test(fn))p.photos.push({fn,url});else if(kind==='floorplans'&&/\.(jpe?g|png|webp|pdf)$/i.test(fn))p.floorplans.push(url);else if(kind==='listing')p.listing.push({name:fn,url});else if(kind==='video'&&fn.endsWith('.webloc')){const txt=await file.text();p.video=(txt.match(/<string>(https?:\/\/[^<]+)<\/string>/)||[])[1]||'';}}}p.photos.sort((a,b)=>(parseInt(a.fn.match(/_(\d+)\./)?.[1])||0)-(parseInt(b.fn.match(/_(\d+)\./)?.[1])||0));p.photos=p.photos.map(x=>x.url);p.cover=p.photos[0]||'';return p;}
$('#openLibrary').onclick=async()=>{if(!window.showDirectoryPicker){alert('Folder access is not supported in this browser. Try Chrome or Edge on desktop.');return}try{const root=await showDirectoryPicker();const found=[];for await(const [,h] of root.entries())if(h.kind==='directory')found.push(await scanProperty(h));if(found.length){properties=found;render();}}catch(e){if(e.name!=='AbortError')alert('Could not open that folder.');}};render();
